# Generated by Django 4.2.7 on 2023-11-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgement_summary_tool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Law',
        ),
    ]
